
DROP TABLE IF EXISTS COSTOESTIMACION CASCADE;
DROP TABLE IF EXISTS OBRA CASCADE;
DROP TABLE IF EXISTS MATERIAL CASCADE;
DROP TABLE IF EXISTS MAQUINARIA CASCADE;
DROP TABLE IF EXISTS EMPLEADO CASCADE;
DROP TABLE IF EXISTS CLIENTE CASCADE;
DROP TABLE IF EXISTS TIPOMAQUINARIA CASCADE;
DROP TABLE IF EXISTS TIPOMATERIAL CASCADE;

CREATE TABLE CLIENTE (
   ID_CLIENTE INT NOT NULL,
   NOMBRECLIENTE CHAR(80),
   CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE EMPLEADO (
   ID_EMPLEADO INT NOT NULL,
   NOMBREEMPLEADO CHAR(80),
   CORREO CHAR(50),
   CLAVE CHAR(15),
   CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE TIPOMAQUINARIA (
   ID_TIPOMAQUINARIA INT NOT NULL,
   TIPOMAQUINARIA CHAR(50),
   CONSTRAINT PK_TIPOMAQUINARIA PRIMARY KEY (ID_TIPOMAQUINARIA)
);

CREATE TABLE TIPOMATERIAL (
   ID_TIPOMATERIAL INT NOT NULL,
   TIPOMATERIAL CHAR(50),
   CONSTRAINT PK_TIPOMATERIAL PRIMARY KEY (ID_TIPOMATERIAL)
);

CREATE TABLE MAQUINARIA (
   ID_MAQUINARIA INT NOT NULL,
   ID_TIPOMAQUINARIA INT,
   NOMBREMAQUINARIA CHAR(50),
   DEPRECIACION INT,
   CONSUMOENERGIAKW DECIMAL(10,2),
   CONSTRAINT PK_MAQUINARIA PRIMARY KEY (ID_MAQUINARIA)
);

CREATE TABLE MATERIAL (
   ID_MATERIALES INT NOT NULL,
   ID_TIPOMATERIAL INT,
   NOMBREMATERIAL CHAR(50),
   DESCRIPCION CHAR(500),
   COSTOUNITARIOMATERIAL DECIMAL(12,2),
   UNIDADMEDIDAMATERIAL CHAR(5),
   CONSTRAINT PK_MATERIAL PRIMARY KEY (ID_MATERIALES)
);

CREATE TABLE OBRA (
   ID_OBRA INT NOT NULL,
   ID_MATERIAL INT,
   ID_CLIENTE INT,
   ID_MAQUINARIA INT,
   TITULOOBRA CHAR(50),
   NOMBREAUTOROBRA CHAR(50),
   PROPIETARIOOBRA CHAR(50),
   NUMEROPAGINAS INT,
   TIRADA INT,
   PORTADA CHAR(500),
   CONSTRAINT PK_OBRA PRIMARY KEY (ID_OBRA)
);

CREATE TABLE COSTOESTIMACION (
   ID_COSTOESTIMACION INT NOT NULL,
   ID_OBRA INT,
   ID_EMPLEADO INT,
   COSTOUNITARIOS DECIMAL(12,2),
   ENERGIAELECTRICA DECIMAL(10,2),
   COSTOPRODUCCION DECIMAL(12,2),
   TOTALESTIMADO DECIMAL(12,2),
   CONSTRAINT PK_COSTOESTIMACION PRIMARY KEY (ID_COSTOESTIMACION)
);

/* Relaciones */
ALTER TABLE COSTOESTIMACION
   ADD CONSTRAINT FK_COSTOEST_REALIZA_EMPLEADO FOREIGN KEY (ID_EMPLEADO)
   REFERENCES EMPLEADO (ID_EMPLEADO)
   ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE COSTOESTIMACION
   ADD CONSTRAINT FK_COSTOEST_REQUIERE_OBRA FOREIGN KEY (ID_OBRA)
   REFERENCES OBRA (ID_OBRA)
   ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MAQUINARIA
   ADD CONSTRAINT FK_MAQUINAR_RELATIONS_TIPOMAQU FOREIGN KEY (ID_TIPOMAQUINARIA)
   REFERENCES TIPOMAQUINARIA (ID_TIPOMAQUINARIA)
   ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MATERIAL
   ADD CONSTRAINT FK_MATERIAL_TIENE_TIPOMATE FOREIGN KEY (ID_TIPOMATERIAL)
   REFERENCES TIPOMATERIAL (ID_TIPOMATERIAL)
   ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE OBRA
   ADD CONSTRAINT FK_OBRA_SUBE_CLIENTE FOREIGN KEY (ID_CLIENTE)
   REFERENCES CLIENTE (ID_CLIENTE)
   ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE OBRA
   ADD CONSTRAINT FK_OBRA_USA_MATERIAL FOREIGN KEY (ID_MATERIAL)
   REFERENCES MATERIAL (ID_MATERIALES)
   ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE OBRA
   ADD CONSTRAINT FK_OBRA_UTILIZA_MAQUINAR FOREIGN KEY (ID_MAQUINARIA)
   REFERENCES MAQUINARIA (ID_MAQUINARIA)
   ON DELETE RESTRICT ON UPDATE RESTRICT;
